#!/usr/bin/env python3
# -*- coding: utf-8 -*-
### Generated by ITinflect-Ctrl
### Repository: https://www.github.com/itinflect-Ctrl

import base64
import re
import tldextract
from datetime import datetime
import os
import urllib.request

def download_gfwlist():
    url = 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt'
    output_file = 'base64.txt'
    # 删除旧文件，确保每次都重新下载
    if os.path.exists(output_file):
        os.remove(output_file)
        print(f'Removed old {output_file}')
    try:
        print('Downloading latest GFWList source file...')
        urllib.request.urlretrieve(url, output_file)
        print(f'Download completed: {output_file}')
    except Exception as e:
        print(f'Download failed: {e}')
        print(f'wget -O {output_file} {url}')
        exit(1)

def is_valid_custom_domain(domain):
    if not domain:
        return False
    if len(domain) > 253:
        return False
    if not re.match(r'^[a-zA-Z0-9.-]+$', domain):
        return False
    invalid_chars = ['[', ']', '*', '?', '<', '>', '"', "'", '|', '\\', ' ', '/', '@', '!', '#', '$', '%', '^', '&', '(', ')', '=', '+', ':', ';', ',']
    return not any(char in domain for char in invalid_chars if char != ' ')

def is_valid_ip(ip):
    if re.match(r'^\d{1,3}(\.\d{1,3}){3}$', ip):
        return all(0 <= int(num) <= 255 for num in ip.split('.'))
    return False

def is_valid_domain(domain):
    if len(domain) > 253:
        return False
    invalid_chars = ['[', ']', '*', '?', '<', '>', '"', "'", '|', '\\', ' ']
    if any(char in domain for char in invalid_chars):
        return False
    if re.match(r'^[a-zA-Z0-9.-]+$', domain) is None:
        return False
    if domain.startswith('-') or domain.endswith('-'):
        return False
    if '.' not in domain:
        return False
    if len(domain.split('.')[-1]) < 2:
        return False
    if not any(c.isalpha() for c in domain.replace('.', '')):
        return False
    return True

def extract_domains_from_gfwlist(file_path):
    with open(file_path, 'rb') as f:
        b64data = f.read()
    content = base64.b64decode(b64data).decode(errors="ignore")
    domains = set()
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('!') or line.startswith('[') or line.startswith('@'):
            continue
        candidates = re.findall(r'([a-zA-Z0-9.-]+\.[a-zA-Z]+)', line)
        for c in candidates:
            if is_valid_domain(c):
                ext = tldextract.extract(c)
                if ext.domain and ext.suffix:
                    sld = ext.domain + '.' + ext.suffix
                    if is_valid_domain(sld):
                        domains.add(sld.lower())
    return domains

def read_custom_domains(file_path='custom_domains.txt'):
    entries = []
    if os.path.exists(file_path):
        print(f"Reading custom domains from {file_path}...")
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                _l = line.strip().lower()
                if not _l or _l.startswith('#'):
                    continue
                if ' ' in _l:
                    domain, ip = _l.split(None, 1)
                    ip = ip.strip()
                    if is_valid_custom_domain(domain) and is_valid_ip(ip):
                        entries.append((domain, ip))
                else:
                    domain = _l
                    if is_valid_custom_domain(domain):
                        entries.append((domain, None))
    else:
        print("custom_domains.txt not found, skipping custom domains.")
    return entries

if __name__ == '__main__':
    DEFAULT_FORWARD = '8.8.8.8'
    download_gfwlist()
    gfw_domains = extract_domains_from_gfwlist('base64.txt')
    custom_domains_raw = read_custom_domains()
    custom_domains_set = set(d for d, _ in custom_domains_raw)
    gfw_domains = sorted(gfw_domains - custom_domains_set)
    all_domains = custom_domains_raw + [(d, None) for d in gfw_domains]
    seen = set()
    dedup_domains = []
    for d, ip in all_domains:
        if d not in seen:
            dedup_domains.append((d, ip))
            seen.add(d)
    with open('gfwlist_sld.txt', 'w', encoding='utf-8') as out:
        for d, ip in dedup_domains:
            out.write(d + '\n')
    with open('gfwlist6_domain.rsc', 'w', encoding='utf-8') as rsc:
        create_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        rsc.write(f'### --- Created at: {create_time} --- ###\n')
        rsc.write(f':log info "Starting to update MikroTik v6 GFWLIST domain rules..."\n')
        rsc.write('/ip dns static remove [find comment=Gfwlist]\n')
        rsc.write('/ip dns static\n')
        for d, ip in dedup_domains:
            fwd_ip = ip if ip else DEFAULT_FORWARD
            escaped_domain = d.replace('.', '\\\\.')
            regexp = f"(\\\\.|^){escaped_domain}\\$"
            rsc.write(f':do {{ add regexp="{regexp}" comment=Gfwlist type=FWD forward-to={fwd_ip} }} on-error={{}}\n')
        rsc.write(':delay 5s;\n')
        rsc.write('/ip dns cache flush\n')
        rsc.write(':log info "Completed updating GFWLIST domain rules."\n')
    print(f'Successfully processed {len(dedup_domains)} domains (custom first)')
    print('Generated files: gfwlist_sld.txt, gfwlist6_domain.rsc')
    print(f'Extracted {len(dedup_domains)} domains. Saved to gfwlist_sld.txt')
